<p>
<a href="/order/order" class = "btn btn-primary">Place Order</a>
</p>
<div class="search">
  <input type="text" name="searchValue" onkeyup="search()" id="searchValue">
</div>
<div class="filterbystatus">
    <h4>
        Filter By Status
    </h4>
    <form action="" method="post">
        <input type="submit" value="Processing" name = "processing" class = "btn btn-primary">
    </form>
    <form action="" method="post">
        <input type="submit" value="Dispatched" name = "dispatch" class = "btn btn-primary">
    </form>
    <form action="" method="post">
        <input type="submit" value="Refund" name = "refunded" class = "btn btn-primary">
    </form>
</div>
<div class="filter">
    <h4>
        Filter By Date
    </h4>
    <form action="" method="post">
        <input type="submit" value="Today" name="today" class = "btn btn-primary">
    </form>
    <form action="" method="post">
        <input type="submit" value="This week" name="week" class = "btn btn-primary">
    </form>
    <form action="" method="post">
        <input type="submit" value="Month" name="month" class = "btn btn-primary">
    </form>
    <form action="" method="post">
      <div class="row my-2" id="custom_date">
      <h4>Custom Date</h4>
        <div class="col-md-3">
        
          <label for="start_date" class="form-label">Start Date(m/d/y)</label>
          <input type="text" class="form-control" name="start_date" id="start_date">
        </div>
        <div class="col-md-3">
          <label for="end_date" class="form-label">End Date(m/d/y)</label>
          <input type="text" class="form-control" name="end_date" id="end_date">
        </div>
        <div class="col-md-3 mt-4">
          <input type="submit" class="btn btn-success" name="custom_date" value="Search">
        </div>
      </div>
    </form>
    <form action="" method="post">
      <div class="row my-2" id="custom_date" style="display: none;">
        <div class="col-md-3">
          <label for="start_date" class="form-label">Start Date(m/d/y)</label>
          <input type="text" class="form-control" name="start_date" id="start_date">
        </div>
        <div class="col-md-3">
          <label for="end_date" class="form-label">End Date(m/d/y)</label>
          <input type="text" class="form-control" name="end_date" id="end_date">
        </div>
        <div class="col-md-3 mt-4">
          <input type="submit" class="btn btn-success" name="custom_date" value="Search">
        </div>
      </div>
    </form>
</div>

<table class="table" id = "myTable">
  <thead>
    <tr>
      <th scope="col">Order ID</th>
      <th scope="col">Product Name</th>
      <th scope="col">Customer Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <?php foreach($results as $value) { ?>
    
  <tbody>
    <tr>
      <td><?php echo $value['_id']; ?></td>
      <td><?php echo $value['product_name']; ?></td>
      <td><?php echo $value['customer_name']; ?></td>
      <td><?php echo $value['quantity']; ?></td>
      <td><?php echo $value['status']; ?></td>     
<form action="/order/changestatus" method="post">
   <td> <select name="status" id="status" onchange="submit()">
       <option value="">None</option>
        <option value="processing">Processing</option>
        <option value="dispatched">Dispatched</option>
        <option value="shipped">Shipped</option>
        <option value="delivered">Delivered</option>
        <option value="refunded">Refunded</option>
  </select>
  <input type="hidden" name="id" value="<?php echo $value['_id']; ?>">
    </td>
    </form>

      <!-- <td><a href="edit?id=<?php echo $value['_id'] ?>"><input type="submit" value="Edit"></a>
      <a href="delete?id=<?php echo $value['_id'] ?>"><input type="submit" value="Delete"></a></td>
      <td><input type = "submit" class = "btn btn-primary" data-id = "<?php echo $value['_id'] ?>" value = "View More" id = "show_popup"></td> -->
      
      
      
    </tr>
  </tbody>
  <?php } ?>
</table>

<div id="popup" class="w-75 bg-dark text-light" style="position: absolute; top:15%; left:12.5%; height:400px; opacity:0.8;">
<div class="d-flex justify-content-end">
    <a  id = "close" class="text-light btn btn-danger">X</a>
</div>

<div id="data" class="w-50 m-auto">

</div>
</div>