<?php




?>
<div class="variations m-3">
<button class="btn btn-primary m-3" id="additional_fields">Additional Fields</button>
<button class="btn btn-primary " id="variationsbtn">Variations</button>
<a href="/index/listproducts" class = "btn btn-primary m-3">Show Products</a>


</div>

<div class="container">
<h2>Edit Products</h2>
<?php foreach($results as $value){ ?>
    <!-- <?php echo "<pre>"; print_r($value); echo count($value[1]['Label'][0]); ?> -->
    <form action="/index/editdetails" method="post">
        <p>
        <label for="Name">Name:</label>
        <input class="" type="text" name="Name" id="" value = "<?php echo $value['Name']; ?>">
        </p>
        <p>
        <label for="Category Name">Category Name:</label>
        <input type="text" name="Category" id="" value="<?php echo $value['Category']; ?>">

        
        </p>
        <p>
        <h3>Additional Fields</h3>
            <div id="new">
                <?php for($i = 0; $i < count($value[1]['Label'][0]); $i++)
                { ?>
                    <input type="text" name="Label[]" id="label" value="<?php echo $value[1]['Label'][0][$i]; ?>">
                    <input type="text" name="Value[]" id="label" value="<?php echo $value[1]['Value'][0][$i]; ?>">

               <?php } ?> 
            </div>
        </p>
        <p>
            <h3>Variations</h3>
            <div id="variations">
            <?php for($i = 0; $i < count($value[0]['Key'][0]); $i++)
                { ?>
                    <input type="text" name="Key[]" id="label" value="<?php echo $value[0]['Key'][0][$i]; ?>">
                    <input type="text" name="Val[]" id="label" value="<?php echo $value[0]['Val'][0][$i]; ?>">

               <?php } ?> 
            </div>
        </p>
        <p>
        <label for="Price">Price:</label>
        <input type="text" name="Price" id="" value= "<?php echo $value['Price']; ?>">
        </p>
        <p>
        <label for="Stock">Stock:</label>        
        <input type="text" name="Stock" id="" value="<?php echo $value['Stock']; ?>">

        </p>
        <input type="hidden" name="id" value="<?php echo $id; ?>">
        <input type="submit" value="Update Product" class="add m-3">
    </form>
    <?php } ?>
</div>

