<div class="variations m-3">
<button class="btn btn-primary m-3" id="additional_fields">Additional Fields</button>
<button class="btn btn-primary " id="variationsbtn">Variations</button>
<a href="index/listproducts" class = "btn btn-primary m-3">Show Products</a>


</div>
<div class="container">
<h2>Add Products</h2>
    <form action="index/addproduct" method="post">
        <p>
        <label for="Name">Name:</label>
        <input class="" type="text" name="Name" id="">
        </p>
        <p>
        <label for="Category Name">Category Name:</label>
        <input type="text" name="Category" id="">

        
        </p>
        <p>
            
            <div id="new">

            </div>
        </p>
        <p>
            <div id="variations">
                <!-- <div id="colors">
                    <input type="checkbox" name="color" id="color" value="Red">Red
                    <input type="checkbox" name="color" id="color" value="Black">Black
                    <input type="checkbox" name="color" id="color" value="White">White
                    <input type="checkbox" name="color" id="color" value="Blue">Blue
                </div>
                <div id="size">
                    <input type="checkbox" name="size" id="color" value="S">S
                    <input type="checkbox" name="size" id="color" value="M">M
                    <input type="checkbox" name="size" id="color" value="L">L
                    <input type="checkbox" name="size" id="color" value="XL">XL
                    
                </div> -->
            </div>
        </p>
        <p>
        <label for="Price">Price:</label>
        <input type="text" name="Price" id="">
        </p>
        <p>
        <label for="Stock">Stock:</label>        
        <input type="text" name="Stock" id="">
        </p>
        <input type="submit" value="Add Product" class="add m-3">
    </form>
</div>

