<?php
namespace Multiple\Frontend\Controllers;


use Phalcon\Mvc\Controller;


class UserproductController extends Controller
{
    public function indexAction()
    {
        
        
        // return '<h1>Hello World!</h1>';
    }
    public function listproductAction()
    {
        $collection = $this->mongo->products;
        $results = $collection->find();
        $this->view->results = $results;
    }
    
}