<?php
// echo "<pre>";
// foreach($data as $val){
//     print_r($val);
// }

?>

<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              
              <th scope="col">CUSTOMER NAME</th>
              <th scope="col">CUSTOMER ID</th>
              <th scope="col">PRODUCT NAME</th>
              <th scope="col">PRODUCT ID</th>
              <th scope="col">QUANTITY</th>
              <th scope="col">STATUS</th>
              
            </tr>
          </thead>
          <tbody>
            <?php
            
             $html="";
             foreach($data as $v) {
               $html.='<form method="POST" action="access"<tr>
               <td>'.$v->username.'</td>
               <td>'.$v->userid.'</td>
               <td>'.$v->name.'</td>
              <td>'.$v->_id.'</td>
              <td>'.$v->quantity.'</td>
               <td>'.$v->status.'</td>
           </tr></form>';
             }
             $html.="";
             echo $html;
           ?> 