<?php
// foreach($results as $value){
//  print_r($value);
// }

?>

<div class="container">
<h2>Edit Products</h2>
<?php foreach($results as $value){ ?>
  
    <form action="/products/editdetails" method="post">
        <p>
        <label for="Name">Name:</label>
        <input class="" type="text" name="Name" id="" value = "<?php echo $value['Name']; ?>">
        </p>
        <p>
        <label for="Category Name">Category Name:</label>
        <input type="text" name="Category" id="" value="<?php echo $value['Category']; ?>">

        
        </p>
        <p>
        <label for="Price">Price:</label>
        <input type="text" name="Price" id="" value= "<?php echo $value['Price']; ?>">
        </p>
        <p>
        <label for="Stock">Stock:</label>        
        <input type="text" name="Stock" id="" value="<?php echo $value['Stock']; ?>">

        </p>
        <input type="hidden" name="id" value="<?php echo $id; ?>">
        <input type="submit" value="Update Product" class="add m-3">
    </form>
    <?php } ?>
</div>

