<div class="container">
<h2>Add Products</h2>
    <form action="/products/addproduct" method="post">
        <p>
        <label for="Name">Name:</label>
        <input class="" type="text" name="Name" id="">
        </p>
        <p>
        <label for="Category Name">Category Name:</label>
        <input type="text" name="Category" id="">
        </p>
        
        <p>
        <label for="Price">Price:</label>
        <input type="text" name="Price" id="">
        </p>
        <p>
        <label for="Stock">Stock:</label>        
        <input type="text" name="Stock" id="">
        </p>
        <input type="submit" value="Add Product" class="add m-3">
    </form>
</div>

